[package]
name = "codespan-derive"
version = "0.1.0"
authors = ["Michael Goulet <michael@errs.io>"]
edition = "2018"

[workspace]
members = [
    "proc",
]

[dependencies]
proc = { path = "./proc/" }
codespan-reporting = "0.11.1"